# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradientdescent <- function(P, n, XtX, L, lambda, maxite, tolobj) {
    .Call('_GADAG2_gradientdescent', PACKAGE = 'GADAG2', P, n, XtX, L, lambda, maxite, tolobj)
}

